language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - python3-pip
      - wget

sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis-setup-linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis-setup-osx.sh; fi

osx_image: xcode9.2

compiler:
  - gcc
  - clang

install: true

script: ./.travis-test.sh
