language: c

os:
  - linux
  - osx

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-pip wget
  - sudo pip3 install meson
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -O "$TRAVIS_BUILD_DIR"/ninja-linux.zip
  - sudo unzip -d /usr/bin/ "$TRAVIS_BUILD_DIR"/ninja-linux.zip

osx_image: xcode9.1

compiler:
  - gcc
  - clang

install: true

script: meson build-meson && ninja -C build-meson
